name: Continuous integration workflow

on: [push]

jobs:
    laravel-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
